#possible keybindings
#https://github.com/leftwm/leftwm/blob/master/src/utils/xkeysym_lookup.rs

#Mod4 = Super key
modkey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
scratchpad = []
#[[scratchpad]]
#name = "MainTerminal" # This is the name which is referenced when calling (case-sensitive)
#value = "xfce4-terminal" # The command to load the application if it isn't started
disable_current_tag_swap = true
focus_behaviour = "Sloppy"
#focus_behaviour = "Driven"
#focus_behaviour = "ClickTo"
focus_new_windows = true


#[[keybind]]
#command = "ToggleScratchPad"
#value = "MainTerminal"
#modifier = []
#key = "F12"

[[keybind]]
command = "Execute"
value = "killall conky"
modifier = ["modkey"]
key = "c"


[[keybind]]
command = "Execute"
value = "arcolinux-logout"
modifier = ["modkey"]
key = "x"


[[keybind]]
command = "Execute"
value = "leftwm-command ToggleFullScreen"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "Execute"
value = "dmenu_run -bw 2 -l 20 -g 4 -p 'Run:'"
modifier = ["modkey","Shift"]
key = "d"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "Execute"
value = "pcmanfm"
modifier = ["modkey"]
key = "n"

[[keybind]]
command = "Execute"
value = "rofi -show drun"
modifier = ["modkey"]
key = "r"

[[keybind]]
command = "Execute"
value = "dm-maim"
modifier = []
key = "Print"

[[keybind]]
command = "Execute"
value = "alacritty -e nvim"
modifier = ["modkey"]
key = "m"

# _          __ _ __        ____  __   ____                  _  __ _           #
#| |    ___ / _| |\ \      / /  \/  | / ___| _ __   ___  ___(_)/ _(_) ___ ___  #
#| |   / _ \ |_| __\ \ /\ / /| |\/| | \___ \| '_ \ / _ \/ __| | |_| |/ __/ __| #
#| |__|  __/  _| |_ \ V  V / | |  | |  ___) | |_) |  __/ (__| |  _| | (__\__ \ #
#|_____\___|_|  \__| \_/\_/  |_|  |_| |____/| .__/ \___|\___|_|_| |_|\___|___/ #
#                                           |_|                                #
#                                                                              #

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "space"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "Execute"
value = "leftwm-command SwapScreens"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "Execute"
value = "leftwm-command SwapScreens"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "MoveWindowToNextWorkspace"
modifier = ["modkey","Shift"]
key = "Left"

[[keybind]]
command = "MoveWindowToNextWorkspace"
modifier = ["modkey","Shift"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control","Alt"]
key = "Left"

[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control","Alt"]
key = "Up"

[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Down"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey", "Shift"]
key = "Tab"

[[keybind]]
command = "FocusNextTag"
modifier = ["Alt"]
key = "Tab"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Alt", "Shift"]
key = "Tab"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 1\""
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 2\""
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 3\""
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 4\""
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 5\""
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 6\""
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 7\""
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 8\""
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 9\""
modifier = ["modkey", "Shift"]
key = "9"
